routes/web.php
<?php

use App\Mail\ExpireSoonEmail;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PlanController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\SignUpController;
use App\Http\Controllers\PaymentController;
use SebastianBergmann\CodeCoverage\Report\Html\Dashboard;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {return view('main');});

Route::get('/member/login', [ MemberController::class, 'login' ] );

Route::get('/member/register', [ MemberController::class, 'register' ]);

Route::get('/member', [ MemberController::class, 'index' ]);

Route::get('/member/profile', [ MemberController::class, 'profile' ]);

Route::get('/dashboard', [MemberController::class, 'index']) ->name('dashboard') ->middleware(['auth']);

Route::middleware(['auth','can:is-admin'])->group(function (){

// --Admin users module
Route::resource('admin/user' , UserController::class);

// --Roles user module
Route::resource('admin/role' , RoleController::class);

// --Plan module
Route::resource('admin/plan', PlanController::class);

// --Payment module
Route::get('admin/payment', [PaymentController::class, 'index'] );


});

Route::resource('signup', SignUpController::class);
Route::get('/signup', [SignUpController::class, 'index'])->name('signup');

Route::get('/signup/review/{id}', [SignUpController::class, 'review']);
Route::post('/signup/go/{payment_gateway}', [SignUpController::class, 'go'])->name('signup.go');

/** PAYMENT GATEWAY REDIRECT */
Route::post('/signup/thankyou/{payment_gateway}', [SignUpController::class, 'thankyou'])->name('signup.thankyou');
Route::get('/signup/thankyou/{payment_gateway}', [SignUpController::class, 'thankyou']);

/** PAYMENT GATEWAY CALLBACK--TAK LEH CHECK/UJI DALAM DEVELOPMENT */
Route::post('/signup/callback/{payment_gateway}', [SignUpController::class, 'payment_callback'])->name('signup.callback');
Route::get('/signup/callback/{payment_gateway}', [SignUpController::class, 'payment_callback']);

Route::view('/rahsia', 'rahsia')->middleware(['auth','can:is-active']);

/**EMAIL VIEW */
// Route::get('/email/expiresoon', function () {
//     return new App\Mail\ExpireSoonEmail();
//     });

Route::get('/email/test',function(){

    $data = [
        'name' => 'wan zul',
        'expire_at' => '2021-01-21'
    ];
    Mail::to('ceasar31@example.net')->send(new ExpireSoonEmail($data));

    echo"email sent";
});

app/Models/Plan.php
<?php

namespace App\Models;

use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Plan extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'price',
        'duration',
    ];
    

    public function getMoneyPriceAttribute()
    {
        return 'RM'. number_format(($this->price / 100), 2);
    }

    public function setNameAttribute($value)
    {
        $this->attributes['name'] = Str::title($value);
    }

    protected $casts = [
        'created_at' => 'datetime:Y-m-d',
    ];
}

app/Http/Controllers/PlanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Plan;
use Illuminate\Http\Request;

class PlanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $plans = Plan::all();
        return view('admin.plan.index', ['plans' => $plans]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.plan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'name' => 'required|min:5|max:100',
            'price' => 'required|numeric',
            'duration' => 'required|integer'
          ]);

          $data['price'] = abs(floor($data['price'] * 100));
  
        $plan = Plan::create($data);
          
          return redirect('/admin/plan')->with('success' , "Pakej langganan <b>{$plan->name} ({$plan->id}) telah berjaya disimpan</b>");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/plan/create.blade.php
@extends('layout.private')
@section('content')

<h1 class="h3 mb-3 text-gray-800">Tambah Pakej Baru</h1>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Isikan maklumat pakej baru</h6>
    </div>
    <div class="card-body">
        <form action="{{route('plan.store')}}" method="post">
            @csrf


            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label">Nama</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control @error('name') is-invalid @enderror" name="name"
                        value="{{old('name')}}">
                    @error('name')
                    <div class="invalid-feeedback">{{$message}}</div>
                    @enderror
                </div>

            </div>

            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label">Harga</label>
                <div class="col-sm-10">
                    <input type="number"
                    min="1"
                    max="99999"
                    step="0.01"
                     class="form-control @error('price') is-invalid @enderror" name="price"
                        value="{{old('price')}}">
                    @error('price')
                    <div class="invalid-feeedback">{{$message}}</div>
                    @enderror
                </div>

            </div>

            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label">Tempoh</label>
                <div class="col-sm-10">
                    <input type="number"
                    min="1"
                    max="99999"
                    step="1"
                     class="form-control @error('duration') is-invalid @enderror" name="duration"
                        value="{{old('duration')}}">
                    @error('duration')
                    <div class="invalid-feeedback">{{$message}}</div>
                    @enderror
                </div>

            </div>
            
            <a href="/admin/plan" class="btn btn-lg btn-secondary">Batal</a>

            <button type="submit" class="btn btn-lg btn-primary">Simpan</button>

        </form>
    </div>
</div>
@endsection

resources/views/admin/plan/index.blade.php
@extends('layout.private')


@section('content')

<div class="d-flex justify-content-between mb-3">

<h1 class="h3 mb-2 text-gray-800">Senarai Pakej Langanan</h1>  

<a href="/admin/plan/create" class="btn btn-secondary">Tambah Pakej</a>

</div>


@if(session('success'))
    <div class="alert alert-success">{!! session('success') !!}</div>
@endif

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Senarai Pakej Langganan</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
       
        <table class="table">
               <thead>
                   <tr>
                       <td>ID</td>
                       <td>Nama</td>
                       <td>HARGA</td>
                       <td>TEMPOH</td>
                       <td></td>
                   </tr>
               </thead>

               <tbody>
  
                    
                   @forelse($plans as $plan)
                   <tr>
                       <td>{{$plan->id}}</td>
                       <td>{{$plan->name}}</td>
                       <!-- <td>RM{{number_format(($plan->price / 100), 2)}}</td> -->
                       <td>{{$plan->money_price}}</td> 
                       <td>{{$plan->duration}}</td>
                       <td>
                            
                       <a href="{{route('plan.edit', $plan->id)}}" class="btn btn-sm btn-primary">EDIT</a>
                       
                       
                       <form method="post" class="d-inline" action="{{route('plan.destroy' , $plan->id)}}" onsubmit="return confirm('Are your sure to delete {{$plan->name}} ({{$plan->id}})')">
                           @csrf
                           @method('DELETE')

                           <button type="submit" class="btn btn-danger btn-sm">DELETE</button>

                       </form>
                           
                       </td>
                   </tr>
                   @empty
                   <tr>
                            <td colspan="5" class="text-center" style="height:50px;">
                                    anda belum membuat apa-apa pakej langganan
                            </td>
                        </tr>
                   @endforelse
                  
               </tbody>
           </table>
          
        </div>
    </div>
</div>

 @endsection